stages:
  - build
  - deploy

  # Needed for Docker in docker build
image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

variables:
  APPLICATION_NAME: outfit-manager
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:next-${CI_COMMIT_SHORT_SHA}

build-job:
  stage: build

  only:
    - next
  tags:
    - dind
    # - talos
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy-job:
  stage: deploy
  only:
    - next
  tags:
    # - dind
    - talos
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s_home/kubernetes-agent:home-talos
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
