apiVersion: apps/v1
kind: Deployment
metadata:
  name: outfit-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outfit-manager
  template:
    metadata:
      labels:
        app: outfit-manager
    spec:
      containers:
        - name: outfit-manager
          image: ${CONTAINER_IMAGE_TAGGED}
          envFrom:
            - secretRef:
                name: auth0-env
            - secretRef:
                name: outfit-manager-env
---
apiVersion: v1
kind: Service
metadata:
  name: outfit-manager
spec:
  ports:
    - port: 3000
      nodePort: 30030
  selector:
    app: outfit-manager
  type: NodePort
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: outfit-manager
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt
#     nginx.ingress.kubernetes.io/proxy-body-size: 5g
#     nginx/client_max_body_size: 5g
# spec:
#   tls:
#     - hosts:
#         - next.outfits.home.maximemoreillon.com
#       secretName: outfit-manager-tls
#   rules:
#     - host: next.outfits.home.maximemoreillon.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: outfit-manager
#                 port:
#                   number: 3000
