apiVersion: apps/v1
kind: Deployment
metadata:
  name: outfit-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: outfit-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: outfit-manager
    spec:
      containers:
        - name: outfit-manager
          image: ${CONTAINER_IMAGE_TAGGED}
          env:
            # S3
            - name: S3_REGION
              value: home
            - name: S3_BUCKET
              value: wardrobe-manager
            - name: S3_USE_SSL
              value: "false"
            - name: S3_ENDPOINT
              value: minio.minio
            - name: S3_PORT
              value: "9000"
            # Auth.js
            - name: AUTH_TRUST_HOST
              value: "true"
            - name: NEXTAUTH_URL
              value: https://outfits.home.maximemoreillon.com
          envFrom:
            - secretRef:
                name: outfit-manager-env-from-vault
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: outfit-manager
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: outfit-manager
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outfit-manager
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

    nginx.ingress.kubernetes.io/proxy-body-size: 5g
    nginx/client_max_body_size: 5g

    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Wardrobe manager
    gethomepage.dev/icon: mdi-hanger
    gethomepage.dev/group: 1P

spec:
  tls:
    - hosts:
        - outfits.home.maximemoreillon.com
      secretName: outfit-manager-tls
  rules:
    - host: outfits.home.maximemoreillon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: outfit-manager
                port:
                  number: 3000
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outfit-manager-env
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: outfit-manager-env-from-vault
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: outfit-manager
